### ISSUE TITLE
Haunt is throwing the following error.

### ISSUE THREAD

**Issue by Tjoosten** [fat/haunt#18]
```
TypeError: Cannot read property 'login' of undefined
    at Repo.getPullRequests (/usr/local/lib/node_modules/haunt/lib/repo.js:143:43)
    at /usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:454:21
    at /usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:185:13
    at /usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:86:13
    at Array.forEach (native)
    at _forEach (/usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:26:24)
    at async.forEach (/usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:85:9)
    at _asyncMap (/usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:184:9)
    at Object.map (/usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:168:23)
    at Object.async.parallel (/usr/local/lib/node_modules/haunt/node_modules/async/lib/async.js:452:19)
```

**Comment by parkr** [comment]
I just got this same thing. If you output `this.data` right before line 143, you see:

> Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

I'll try to see if I can fix this.

**Comment by Tjoosten** [comment]
Your a hero! Now we need to wait on @fat
